#!/usr/bin/env bash
# First-run setup for the nav-stack module.
#
# Default (ROS-free / builtin slam + nav):
#   1. Create the Python venv and pip-install module requirements.
#   2. If ROS 2 is already present, record it in .ros_env (no apt install).
#
# Optional ROS backends (slam_backend: slam_toolbox, nav_backend: nav2):
#   Set REQUIRE_ROS=1 (or INSTALL_ROS=1) in the module env and re-run setup.
#   That path verifies Ubuntu, selects a ROS 2 distro, and apt-installs
#   ROS + Nav2 + slam_toolbox when AUTO_INSTALL_DEPS=1.
#
# Environment:
#   REQUIRE_ROS=1         enforce Ubuntu + install/verify ROS/Nav2 (default: 0)
#   INSTALL_ROS=1         alias for REQUIRE_ROS=1
#   AUTO_INSTALL_DEPS=1   apt-install missing ROS/Nav2 when REQUIRE_ROS=1
#                         (default: 1 when REQUIRE_ROS=1, else unused)
#   ROS_DISTRO            force a distro (e.g. kilted on Ubuntu 24.04)
#   ROS_APT_TESTING=1     use ros-testing apt repo when Nav2 debs are missing
#   ROS_ENV               if already set and valid, skip distro auto-selection
set -euo pipefail

cd "$(dirname "$0")"

# INSTALL_ROS is a documented alias for REQUIRE_ROS.
if [ "${INSTALL_ROS:-0}" = "1" ]; then
    REQUIRE_ROS=1
fi
REQUIRE_ROS="${REQUIRE_ROS:-0}"
ROS_ENV_FILE=".ros_env"
VENV_NAME=".venv"
PYTHON=${PYTHON:-python3}

log() { echo "[nav-stack setup] $*"; }
warn() { echo "[nav-stack setup] WARNING: $*" >&2; }
die() { echo "[nav-stack setup] ERROR: $*" >&2; exit 1; }

# ROS setup.bash scripts reference optional vars (e.g. AMENT_TRACE_SETUP_FILES) that
# are unset on a fresh shell; set -u would abort while sourcing them.
source_ros_setup() {
    local setup_file="$1"
    set +u
    # shellcheck disable=SC1090
    source "${setup_file}"
    set -u
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

as_root() {
    if [ "$(id -u)" -eq 0 ]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        die "need root or sudo to install system packages (set AUTO_INSTALL_DEPS=0 to skip)"
    fi
}

# ---------------------------------------------------------------------------
# Ubuntu + ROS distro selection (REQUIRE_ROS path only)
# ---------------------------------------------------------------------------
detect_ubuntu() {
    if [ ! -f /etc/os-release ]; then
        die "not a Linux system with /etc/os-release; ROS 2 install is Ubuntu-only (builtin slam/nav do not need ROS — omit REQUIRE_ROS)"
    fi
    # shellcheck disable=SC1091
    . /etc/os-release
    if [ "${ID:-}" != "ubuntu" ]; then
        die "unsupported OS ${ID:-unknown}; slam_toolbox/Nav2 require Ubuntu 22.04, 24.04, or 26.04 (builtin slam/nav work without ROS — omit REQUIRE_ROS)"
    fi
    UBUNTU_VERSION="${VERSION_ID:-}"
    UBUNTU_CODENAME="${VERSION_CODENAME:-}"
    log "detected Ubuntu ${UBUNTU_VERSION} (${UBUNTU_CODENAME})"
}

select_ros_distro() {
    if [ -n "${ROS_DISTRO:-}" ]; then
        log "using ROS_DISTRO from environment: ${ROS_DISTRO}"
        return
    fi
    case "${UBUNTU_VERSION}" in
        22.04) ROS_DISTRO=humble ;;
        24.04) ROS_DISTRO=jazzy ;;   # LTS; set ROS_DISTRO=kilted to use Kilted Kaiju instead
        26.04) ROS_DISTRO=lyrical ;;
        *)
            die "unsupported Ubuntu ${UBUNTU_VERSION}; supported: 22.04 (Humble), 24.04 (Jazzy/Kilted), 26.04 (Lyrical)"
            ;;
    esac
    export ROS_DISTRO
    log "selected ROS 2 distro: ${ROS_DISTRO} for Ubuntu ${UBUNTU_VERSION}"
}

resolve_ros_setup() {
    if [ -n "${ROS_ENV:-}" ] && [ -f "${ROS_ENV}" ]; then
        ROS_SETUP="${ROS_ENV}"
        # Infer distro from path when possible: /opt/ros/<distro>/setup.bash
        if [ -z "${ROS_DISTRO:-}" ]; then
            ROS_DISTRO="$(basename "$(dirname "${ROS_SETUP}")")"
            export ROS_DISTRO
        fi
        log "using ROS_ENV=${ROS_SETUP}"
        return
    fi
    ROS_SETUP="/opt/ros/${ROS_DISTRO}/setup.bash"
}

write_ros_env_file() {
    cat > "${ROS_ENV_FILE}" <<EOF
# Generated by setup.sh — sourced by run.sh when ROS_ENV is unset in the module env.
ROS_DISTRO=${ROS_DISTRO}
ROS_ENV=${ROS_SETUP}
EOF
    log "wrote ${ROS_ENV_FILE} (ROS_DISTRO=${ROS_DISTRO})"
}

write_ros_free_env_file() {
    cat > "${ROS_ENV_FILE}" <<'EOF'
# Generated by setup.sh — ROS not configured (builtin slam / nav).
# For slam_toolbox or Nav2: set REQUIRE_ROS=1 in the module env and re-run setup
# (Ubuntu 22.04/24.04/26.04 with apt install of ROS 2 + Nav2 + slam_toolbox).
EOF
    log "wrote ${ROS_ENV_FILE} (ROS-free / builtin path)"
}

# ---------------------------------------------------------------------------
# Optional discovery when REQUIRE_ROS is off
# ---------------------------------------------------------------------------
discover_existing_ros() {
    # Prefer an explicit ROS_ENV if the file exists.
    if [ -n "${ROS_ENV:-}" ] && [ -f "${ROS_ENV}" ]; then
        ROS_SETUP="${ROS_ENV}"
        if [ -z "${ROS_DISTRO:-}" ]; then
            ROS_DISTRO="$(basename "$(dirname "${ROS_SETUP}")")"
            export ROS_DISTRO
        fi
        log "discovered ROS via ROS_ENV=${ROS_SETUP}"
        return 0
    fi
    local distro setup
    for distro in jazzy humble kilted lyrical iron rolling; do
        setup="/opt/ros/${distro}/setup.bash"
        if [ -f "${setup}" ]; then
            ROS_DISTRO="${distro}"
            ROS_SETUP="${setup}"
            export ROS_DISTRO
            log "discovered existing ROS 2 at ${ROS_SETUP}"
            return 0
        fi
    done
    return 1
}

# ---------------------------------------------------------------------------
# apt / ROS installation
# ---------------------------------------------------------------------------
apt_pkg_installed() {
    dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "install ok installed"
}

apt_pkg_available() {
    apt-cache show "$1" >/dev/null 2>&1
}

nav_packages_available() {
    apt_pkg_available "ros-${ROS_DISTRO}-nav2-bringup" \
        && apt_pkg_available "ros-${ROS_DISTRO}-slam-toolbox"
}

install_ros_apt_source_deb() {
    local deb_name="$1"
    need_cmd curl
    local version url deb
    version="$(curl -fsSL https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest \
        | grep -F '"tag_name"' | head -1 | awk -F'"' '{print $4}')"
    [ -n "${version}" ] || die "could not determine ros-apt-source release version"
    url="https://github.com/ros-infrastructure/ros-apt-source/releases/download/${version}/${deb_name}_${version}.${UBUNTU_CODENAME}_all.deb"
    deb="/tmp/${deb_name}_${UBUNTU_CODENAME}.deb"
    curl -fsSL -o "${deb}" "${url}" || die "failed to download ${deb_name} for ${UBUNTU_CODENAME}"
    as_root dpkg -i "${deb}"
    as_root apt-get update -qq
}

ensure_ros_apt_source() {
    # Skip if any ros-$ROS_DISTRO-* package is already known to apt.
    if apt-cache show "ros-${ROS_DISTRO}-ros-base" >/dev/null 2>&1; then
        return
    fi
    log "configuring ROS 2 apt source for ${ROS_DISTRO} on ${UBUNTU_CODENAME}"
    install_ros_apt_source_deb "ros2-apt-source"
}

ensure_ros_testing_apt_source() {
    if apt_pkg_available "ros-${ROS_DISTRO}-ros-base"; then
        # ros-testing replaces ros-apt-source; packages may already be indexed.
        if nav_packages_available; then
            return
        fi
    fi
    log "configuring ROS 2 testing apt source for ${ROS_DISTRO} on ${UBUNTU_CODENAME}"
    install_ros_apt_source_deb "ros2-testing-apt-source"
}

nav_packages_unavailable_message() {
    cat >&2 <<EOF
[nav-stack setup] ERROR: Nav2 / slam_toolbox deb packages are not available for ROS 2 ${ROS_DISTRO} on Ubuntu ${UBUNTU_VERSION}.

  apt could not find:
    ros-${ROS_DISTRO}-navigation2
    ros-${ROS_DISTRO}-nav2-bringup
    ros-${ROS_DISTRO}-slam-toolbox

  Nav2 and slam_toolbox are not yet published for Lyrical on Pi-class arm64 images.
  Recommended: re-image the Pi with Ubuntu 24.04 LTS and use Jazzy (setup.sh default).

  Optional: set ROS_APT_TESTING=1 in the module env and re-run setup to try ros-testing.
  Otherwise install Nav2 + slam_toolbox yourself and set AUTO_INSTALL_DEPS=0.

  Builtin slam/nav do not need ROS — omit REQUIRE_ROS for the ROS-free path.
EOF
}

ros_base_installed() {
    apt_pkg_installed "ros-${ROS_DISTRO}-ros-base" || [ -f "${ROS_SETUP}" ]
}

nav_packages_installed() {
    apt_pkg_installed "ros-${ROS_DISTRO}-nav2-bringup" \
        && apt_pkg_installed "ros-${ROS_DISTRO}-slam-toolbox"
}

install_ros_base() {
    log "installing ros-${ROS_DISTRO}-ros-base"
    as_root apt-get install -y --no-install-recommends \
        "ros-${ROS_DISTRO}-ros-base"
}

ensure_nav_packages_in_apt() {
    if nav_packages_available; then
        return
    fi
    if [ "${ROS_APT_TESTING:-0}" = "1" ] || [ "${UBUNTU_VERSION}" = "26.04" ]; then
        warn "Nav2 packages missing from main ROS apt repo; trying ros-testing"
        ensure_ros_testing_apt_source
    fi
    if nav_packages_available; then
        return
    fi
    nav_packages_unavailable_message
    exit 1
}

install_nav_packages() {
    ensure_nav_packages_in_apt
    log "installing Nav2 + slam_toolbox for ${ROS_DISTRO}"
    as_root apt-get install -y --no-install-recommends \
        "ros-${ROS_DISTRO}-navigation2" \
        "ros-${ROS_DISTRO}-nav2-bringup" \
        "ros-${ROS_DISTRO}-slam-toolbox"
}

verify_ros_packages() {
    source_ros_setup "${ROS_SETUP}"
    local pkg
    for pkg in slam_toolbox nav2_bringup; do
        if ! ros2 pkg prefix "${pkg}" >/dev/null 2>&1; then
            die "ROS package '${pkg}' not found after install; check ${ROS_DISTRO} support on Ubuntu ${UBUNTU_VERSION}"
        fi
    done
    log "verified ros2 packages: slam_toolbox, nav2_bringup"
}

ensure_system_ros() {
    # Default AUTO_INSTALL_DEPS to 1 only on the REQUIRE_ROS path.
    AUTO_INSTALL_DEPS="${AUTO_INSTALL_DEPS:-1}"

    resolve_ros_setup

    if ros_base_installed && nav_packages_installed && [ -f "${ROS_SETUP}" ]; then
        log "ROS 2 ${ROS_DISTRO} and Nav2 packages already present"
        write_ros_env_file
        verify_ros_packages
        return
    fi

    if [ "${AUTO_INSTALL_DEPS}" != "1" ]; then
        die "ROS 2 / Nav2 not installed and AUTO_INSTALL_DEPS=0; install manually or re-run with AUTO_INSTALL_DEPS=1"
    fi

    log "installing missing ROS 2 / Nav2 dependencies (AUTO_INSTALL_DEPS=1)"
    as_root apt-get update -qq
    # venv + many ROS Python bindings expect these on minimal images.
    as_root apt-get install -y --no-install-recommends \
        curl ca-certificates python3 python3-venv python3-pip

    ensure_ros_apt_source

    if ! ros_base_installed; then
        install_ros_base
    fi
    if ! nav_packages_installed; then
        install_nav_packages
    fi

    [ -f "${ROS_SETUP}" ] || die "ROS setup not found at ${ROS_SETUP} after install"
    write_ros_env_file
    verify_ros_packages
}

# ---------------------------------------------------------------------------
# Python venv
# ---------------------------------------------------------------------------
ensure_python_venv() {
    if ! "$PYTHON" --version >/dev/null 2>&1; then
        die "python3 not found on PATH"
    fi
    if [ ! -d "${VENV_NAME}" ]; then
        log "creating virtualenv in ${VENV_NAME}"
        if ! "$PYTHON" -m venv --system-site-packages "${VENV_NAME}"; then
            die "failed to create ${VENV_NAME}; install python3-venv (e.g. apt install python3-venv) and re-run setup"
        fi
    fi
    # shellcheck disable=SC1091
    source "${VENV_NAME}/bin/activate"
    pip install --upgrade pip -q
    pip install -r requirements.txt -q
    log "Python dependencies installed"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    ensure_python_venv

    if [ "${REQUIRE_ROS}" = "1" ]; then
        log "REQUIRE_ROS=1 — installing/verifying ROS 2 + Nav2 + slam_toolbox"
        detect_ubuntu
        # Honour a preconfigured ROS_ENV before picking the Ubuntu-default distro.
        if [ -n "${ROS_ENV:-}" ] && [ -f "${ROS_ENV}" ]; then
            ROS_SETUP="${ROS_ENV}"
            if [ -z "${ROS_DISTRO:-}" ]; then
                ROS_DISTRO="$(basename "$(dirname "${ROS_SETUP}")")"
                export ROS_DISTRO
            fi
            log "using preconfigured ROS_ENV=${ROS_ENV} (distro=${ROS_DISTRO})"
        else
            select_ros_distro
        fi
        ensure_system_ros
        log "setup complete (ROS ${ROS_DISTRO} on Ubuntu ${UBUNTU_VERSION}; REQUIRE_ROS=1)"
        return
    fi

    # ROS-free default: no Ubuntu gate. Record ROS if already on the machine so
    # slam_toolbox / Nav2 can still be selected later without a second apt pass.
    if discover_existing_ros; then
        write_ros_env_file
        log "setup complete (ROS-free default; found existing ROS ${ROS_DISTRO} at ${ROS_SETUP})"
        log "builtin slam/nav need no ROS; for forced reinstall set REQUIRE_ROS=1"
    else
        write_ros_free_env_file
        log "setup complete (ROS-free / builtin slam + nav)"
        log "for slam_toolbox or Nav2: set REQUIRE_ROS=1 and re-run setup on Ubuntu 22.04/24.04/26.04"
    fi
}

main "$@"
